"""Common API schemas: health checks, error responses, and shared types."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class HealthStatus(StrEnum):
    """Overall health status."""

    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"


class ComponentStatus(StrEnum):
    """Individual component status within a readiness check."""

    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


class DependencyStatus(BaseModel):
    """Status of a single dependency (e.g. PostgreSQL, Qdrant, OpenSearch)."""

    name: str = Field(description="Human-readable component name")
    status: ComponentStatus = Field(description="Current component status")
    latency_ms: float | None = Field(
        default=None,
        description="Observed latency in milliseconds, if measured",
    )
    error: str | None = Field(
        default=None,
        description="Error message if unhealthy (never exposes credentials or stack traces)",
    )


class HealthResponse(BaseModel):
    """Response for GET /health."""

    status: HealthStatus = Field(description="Overall application health")
    version: str = Field(description="Application version")


class ReadinessResponse(BaseModel):
    """Response for GET /ready."""

    status: HealthStatus = Field(description="Overall readiness status")
    checked_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of the readiness check",
    )
    dependencies: list[DependencyStatus] = Field(
        default_factory=list,
        description="Status of each dependency",
    )


class ErrorDetail(BaseModel):
    """Structured error payload returned in all API error responses."""

    code: str = Field(
        description="Machine-readable error code, e.g. DOCUMENT_NOT_FOUND",
    )
    message: str = Field(
        description="Human-readable explanation of what went wrong",
    )
    request_id: str | None = Field(
        default=None,
        description="Request ID for tracing this specific error",
    )


class ErrorResponse(BaseModel):
    """Standard error envelope for all 4xx/5xx responses.

    Stack traces, credentials, and internal paths are NEVER included.
    """

    error: ErrorDetail = Field(description="Error details")


# ---------------------------------------------------------------------------
# Shared query params / headers
# ---------------------------------------------------------------------------

class RequestID(BaseModel):
    """Mixin/header model for request ID propagation."""

    request_id: str | None = Field(
        default=None,
        description="Unique request ID (generated by the server if not provided)",
    )
